In [2]:
import torch

In [6]:
x = torch.tensor([1,2,3]) # torch is a multidimensional array 

In [4]:
y = torch.tensor([4,5,6])

In [5]:
print(x*y)

tensor([ 4, 10, 18])


In [7]:
z = torch.zeros([2,3])

In [8]:
z

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
z.shape

torch.Size([2, 3])

In [10]:
rand_val= torch.rand([2,5])

In [11]:
rand_val

tensor([[0.6986, 0.4932, 0.7309, 0.2728, 0.0127],
        [0.7166, 0.0025, 0.7411, 0.5792, 0.8425]])

In [12]:
# Instead of reshape we use the view method (faltten operation) to change 
# the size of n array specifically useful while using any CNN or Deep 
# Network so input needs to change according to input 

In [13]:
rand_val.view([1,10])

tensor([[0.6986, 0.4932, 0.7309, 0.2728, 0.0127, 0.7166, 0.0025, 0.7411, 0.5792,
         0.8425]])

In [15]:
rand_val # still not change because the method returns the rehape array 
# we have to store its reusult 

tensor([[0.6986, 0.4932, 0.7309, 0.2728, 0.0127],
        [0.7166, 0.0025, 0.7411, 0.5792, 0.8425]])

In [16]:
rand_reshape = rand_val.view([1,10])

In [17]:
rand_reshape

tensor([[0.6986, 0.4932, 0.7309, 0.2728, 0.0127, 0.7166, 0.0025, 0.7411, 0.5792,
         0.8425]])